services:
  nats1:
    image: nats:2.10-alpine  # Gunakan versi stabil
    hostname: nats1
    container_name: nats1
    command: [
      "--cluster_name", "NATS_CLUSTER",
      "--server_name", "nats1",
      "--cluster", "nats://nats1:6222",
      "--routes", "nats://nats2:6222,nats://nats3:6222",
      "--jetstream",
      "--store_dir", "/data",
      "--max_memory", "1G",
      "--max_file_store", "5G",
      "--cluster_peers", "nats1,nats2,nats3",  # Auto-discovery
      "--cluster_protocol", "2"  # Protokol versi terbaru
    ]
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - nats1-data:/data
    healthcheck:
      test: ["CMD-SHELL", "nats server ping --json || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nats2:
    image: nats:2.10-alpine
    hostname: nats2
    container_name: nats2
    command: [
      "--cluster_name", "NATS_CLUSTER",
      "--server_name", "nats2",
      "--cluster", "nats://nats2:6222",
      "--routes", "nats://nats1:6222,nats://nats3:6222",
      "--jetstream",
      "--store_dir", "/data",
      "--max_memory", "1G",
      "--max_file_store", "5G",
      "--cluster_peers", "nats1,nats2,nats3",
      "--cluster_protocol", "2"
    ]
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    volumes:
      - nats2-data:/data
    depends_on:
      nats1:
        condition: service_healthy

  nats3:
    image: nats:2.10-alpine
    hostname: nats3
    container_name: nats3
    command: [
      "--cluster_name", "NATS_CLUSTER",
      "--server_name", "nats3",
      "--cluster", "nats://nats3:6222",
      "--routes", "nats://nats1:6222,nats://nats2:6222",
      "--jetstream",
      "--store_dir", "/data",
      "--max_memory", "1G",
      "--max_file_store", "5G",
      "--cluster_peers", "nats1,nats2,nats3",
      "--cluster_protocol", "2"
    ]
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    volumes:
      - nats3-data:/data
    depends_on:
      nats2:
        condition: service_healthy

volumes:
  nats1-data:
    driver: local
  nats2-data:
    driver: local
  nats3-data:
    driver: local

networks:
  default:
    name: nats_network
    driver: bridge